# Trying to print x without assigning any value for it
print("\n----- Problem without handling exceptions -----")
y = 5
print(x)
print(y)

# Without the try block, there will be an run time error and raise an error:
# It will give: ---> NameError: name 'x' is not defined
# It will not print y value, although value was assigned


